name: dmelodies
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.11.5
  - cloudpickle=1.3.0
  - cytoolz=0.10.1
  - dask-core=2.10.1
  - dbus=1.13.12
  - decorator=4.4.1
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - imageio=2.6.1
  - intel-openmp=2019.1
  - jpeg=9b
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.36
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - ncurses=6.1
  - networkx=2.4
  - ninja=1.8.2
  - numpy=1.15.4
  - numpy-base=1.15.4
  - olefile=0.46
  - openssl=1.1.1d
  - pandas=1.0.1
  - pcre=8.43
  - pillow=5.4.1
  - pip=18.1
  - pycparser=2.19
  - pymongo=3.7.2
  - pyqt=5.9.2
  - python=3.7.2
  - pytorch=1.0.0
  - pytz=2019.3
  - pywavelets=1.1.1
  - qt=5.9.7
  - readline=7.0
  - scikit-image=0.16.2
  - setuptools=41.0.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.8
  - toolz=0.10.0
  - torchvision=0.2.1
  - tornado=6.0.3
  - tqdm=4.29.1
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.9.0
    - asn1crypto==0.24.0
    - astor==0.8.1
    - bcrypt==3.1.6
    - click==7.0
    - cryptography==2.5
    - cycler==0.10.0
    - dill==0.3.1.1
    - disentanglement-lib==1.4
    - future==0.18.2
    - gast==0.3.3
    - gin-config==0.3.0
    - google-pasta==0.1.8
    - grpcio==1.27.1
    - h5py==2.10.0
    - joblib==0.14.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.0.1
    - markdown==3.2.1
    - matplotlib==3.0.2
    - mido==1.2.9
    - music21==5.5.0
    - paramiko==2.4.2
    - pretty-midi==0.2.8
    - protobuf==3.11.3
    - pyasn1==0.4.5
    - pynacl==1.3.0
    - pyparsing==2.3.1
    - pypianoroll==0.5.3
    - python-dateutil==2.7.5
    - scikit-learn==0.22.1
    - scipy==1.2.0
    - seaborn==0.10.0
    - simplejson==3.17.0
    - sklearn==0.0
    - sshtunnel==0.1.4
    - tensorboard==1.14.0
    - tensorboard-logger==0.1.0
    - tensorboardx==2.0
    - tensorflow-estimator==1.14.0
    - tensorflow-gpu==1.14.0
    - tensorflow-hub==0.7.0
    - tensorflow-probability==0.7.0
    - termcolor==1.1.0
    - werkzeug==1.0.0
    - wrapt==1.11.2

